- 분석 제공 대상이 의사
- 목표 변수 : '수술시간'
- 설명 변수 지정 최소 5개 이상(범주형과 연속형 섞여 있음)
- DDA/README.md : 변수 설명/데이터 type/이유
- 추출, 수술시간이 중앙값 이상인 것.
- 요약 : 수술시간에 가장 영향을 주는 항목 3가지 확인

In [1]:
import pandas as pd

In [2]:
df_ROS = pd.read_csv('../../datasets/RecurrenceOfSurgery.csv')

In [3]:
df_ROS.columns

Index(['Unnamed: 0', '환자ID', 'Large Lymphocyte', 'Location of herniation',
       'ODI', '가족력', '간질성폐질환', '고혈압여부', '과거수술횟수', '당뇨여부', '말초동맥질환여부', '빈혈여부',
       '성별', '스테로이드치료', '신부전여부', '신장', '심혈관질환', '암발병여부', '연령', '우울증여부', '입원기간',
       '입원일자', '종양진행여부', '직업', '체중', '퇴원일자', '헤모글로빈수치', '혈전합병증여부', '환자통증정도',
       '흡연여부', '통증기간(월)', '수술기법', '수술시간', '수술실패여부', '수술일자', '재발여부', '혈액형',
       '전방디스크높이(mm)', '후방디스크높이(mm)', '지방축적도', 'Instability', 'MF + ES',
       'Modic change', 'PI', 'PT', 'Seg Angle(raw)', 'Vaccum disc', '골밀도',
       '디스크단면적', '디스크위치', '척추이동척도', '척추전방위증'],
      dtype='object')

In [ ]:
#### 수술기법에 따라 수술시간 추이 확인

In [11]:
df_ROS_Q = df_ROS[['종양진행여부', '수술기법', '연령', '환자통증정도','수술실패여부','수술시간']]
# df_ROS_Q.iloc[:3]
df_ROS_Q

      종양진행여부  수술기법  연령  환자통증정도  수술실패여부  수술시간
0          0  TELD  66      10       0  68.0
1          0  TELD  47      10       0  31.0
2          0  TELD  39       7       0  78.0
3          0  TELD  40       7       0  73.0
4          0  TELD  42       7       0  29.0
...      ...   ...  ..     ...     ...   ...
1889       1   NaN  59       7       0  80.0
1890       0   NaN  42       7       0  20.0
1891       0  IELD  61       7       0  50.0
1892       0   NaN  29       7       0  25.0
1893       0   NaN  30       8       0  45.0

[1894 rows x 6 columns]

In [21]:
df_ROS_Q.pivot_table(index='수술시간', columns=['연령', '환자통증정도','수술실패여부'], aggfunc= 'size')

연령      15  16      17                      18  ...  76  77          78      \
환자통증정도  7   7   10  1   2   7   8       9   2   ...  9   7   9   10  7   8
수술실패여부   0   0   0   0   0   0   0   1   0   0  ...   0   0   0   1   0   0
수술시간                                            ...
5.0    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN
6.0    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN
7.0    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN
10.0   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN
12.0   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
152.0  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN
155.0  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN
165.0  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN
190.0  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN
220.0  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN

연령      79      80  84
환자통증정도  7       7   7
수술실패여부   0   1   0   0
수술시간
5.0    NaN NaN NaN NaN
6.0    NaN NaN NaN NaN
7.0    NaN NaN NaN NaN
10.0   NaN NaN NaN NaN
12.0   NaN NaN NaN NaN
...     ..  ..  ..  ..
152.0  NaN NaN NaN NaN
155.0  NaN NaN NaN NaN
165.0  NaN NaN NaN NaN
190.0  NaN NaN NaN NaN
220.0  NaN NaN NaN NaN

[134 rows x 461 columns]